#!/usr/bin/env python3
"""Third stage: roster.json -> src/spells/spells.js, the page's only data file.

Keys are short because there are 589 of them and this file is downloaded whole;
the page maps them back to names in one place. Nothing is summarised here — the
prose is the books' own text, split into the paragraphs and lists they set.
"""
import json, re
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent.parent / "src" / "spells" / "spells.js"

BOOKS = {
    "ll":    {"t": "Legends & Legacies",     "s": "Kibbles' Compendium of Legends & Legacies"},
    "llb":   {"t": "Legends & Legacies",     "s": "Kibbles' Compendium of Legends & Legacies — Blood Magic"},
    "cc":    {"t": "Craft and Creation",     "s": "Kibbles' Compendium of Craft and Creation"},
    "retia": {"t": "Lyre's Guide to Retia",  "s": "Lyre's Guide to Retia — Land of Industry"},
}

# The eleven groups Retia's Spell Groups section defines, in the book's words,
# plus the one it uses without defining. Shown when a spell carries the tag.
GROUPS = {
    "Altissima-Cor’s Arcane Arts": "Crystal-born arcana out of Altissima-Cor.",
    "Blood of Cineris": "Magic paid for in blood, after the manner of Cineris.",
    "Chromatic Convocation": "Draconic colour magic.",
    "Daemoturgy": "Fiend-craft — power borrowed from below.",
    "Eidomancy": "Soul magic. Eidomancy spells hit harder than their level suggests; treat them as a tier above.",
    "Epic of Duality": "Paired magic, working on two things at once.",
    "Legacy of Gold": "The gilded tradition.",
    "Nine Branch Arts": "The nine-branch school.",
    "Ossenheimer’s Memoirs": "Spells recorded in Ossenheimer's memoirs.",
    "Sky-Keeper’s Arcana": "Storm and sky magic of the Sky-Keepers.",
    "Whisperwood Tome": "Spells out of the Whisperwood tome.",
    "Skulker’s Grimoire": "Used on fourteen spells but never defined in the book's Spell Groups section.",
    # Printed on Eviscerate (p. 554) and nowhere else. Left as printed rather
    # than corrected, because the book gives no way to tell which it meant.
    "Sky-Keeper’s Grimoire": "Printed on this one spell only, and on no other. "
        "The book's Spell Groups section defines no such group — it is most "
        "likely a misprint for Sky-Keeper's Arcana or Skulker's Grimoire, and "
        "the book does not say which.",
}


def blk(b):
    """['p'|'li', text] for prose; ['tbl', [row, ...]] for a table."""
    return [b["t"], b["rows"] if b["t"] == "tbl" else b["text"]]


def main():
    R = json.load(open(HERE / "roster.json"))
    R.sort(key=lambda r: (r["name"].lower(), r["book"]))

    out = []
    for r in R:
        s = {
            "k": r["entryKey"], "n": r["name"], "l": r["level"],
            "s": r["school"], "sa": r["schoolAbbr"], "c": r["classes"],
            "bk": r["book"], "p": r["page"],
            "ct": r["castingTime"], "rg": r["range"],
            "cp": r["componentsRaw"], "d": r["duration"],
            "b": [blk(b) for b in r["bodyBlocks"]],
        }
        if r["higherBlocks"]:
            s["h"] = [blk(b) for b in r["higherBlocks"]]
        if r.get("review"): s["rv"] = 1
        if r["concentration"]: s["con"] = 1
        if r["ritual"]:        s["rit"] = 1
        if r["legacy"]:        s["leg"] = 1
        if r["bloodMagic"]:    s["bm"] = 1
        if r["magicSource"]:   s["ms"] = r["magicSource"]
        if r["groups"]:        s["g"] = r["groups"]
        if r.get("classesInferred"): s["ci"] = 1
        if r.get("alsoIn"):
            s["also"] = [[a["book"], a["page"]] for a in r["alsoIn"]]
        out.append(s)

    payload = {"books": BOOKS, "groups": GROUPS, "spells": out}
    js = ("/* Spell Compendium — content, generated by tools/spells/emit.py.\n"
          "   Spell text is transcribed from the three homebrew books rather than\n"
          "   summarised; paragraphs and lists follow the printed page. */\n"
          "window.SPELLDATA = " + json.dumps(payload, ensure_ascii=False,
                                             separators=(",", ":")) + ";\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js, encoding="utf-8")

    assert not re.search(r"(?i)dhruv|order\s*#\s*\d", js), "watermark leaked into spells.js"
    print(f"wrote {OUT.relative_to(OUT.parents[2])}  {len(out)} spells  "
          f"{len(js)/1024:.0f} KB")


if __name__ == "__main__":
    main()
